### ISSUE TITLE
ParameterStoreから情報取得できるようにする

### ISSUE THREAD

**Issue by nannany** [tokyo-forest/omron-fitbit-datatransfer#5]

**Comment by nannany** [comment]
google driveアクセスする用の秘密情報をparameter storeに入れた。

**Comment by nannany** [comment]
ローカルではできた。実際にLambdaにあげると権限不足で落ちる。

```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the GetParameters operation: User: arn:aws:sts::948494934800:assumed-role/omron-fitbit-datatran-HelloWorldFunctionRole-FTOHBV9PZ8BN/omron-fitbit-datatran-HelloWorldFunction-WwG24nGuAwWp is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:ap-northeast-1:948494934800:parameter/google-drive-parameter Traceback (most recent call last):   File "/var/task/app.py", line 15, in lambda_handler     param_value = get_parameters("google-drive-parameter")   File "/var/task/app.py", line 69, in get_parameters     response = ssm.get_parameters(   File "/var/task/botocore/client.py", line 386, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/task/botocore/client.py", line 705, in _make_api_call     raise error_class(parsed_response, operation_name)
```
